### ISSUE TITLE
Search remains on page navigation

### ISSUE THREAD

**Issue by jdtzmn** [FNNDSC/ChRIS_store_ui#10]
After searching in the navbar and then clicking on a different page, the search term remains.

**Comment by gagansk** [comment]
I am unable to reproduce this issue. Has this been resolved already?

**Comment by jdtzmn** [comment]
@gagansk The issue has *not* been resolved, but at some point it was broken (since the search feature no longer works).

**Comment by DivyanshiSingh** [comment]
I would like to take this up. First I will try to reproduce it and then will resolve it @mairin

**Comment by mairin** [comment]
Hi @DivyanshiSingh - I have assigned you https://github.com/FNNDSC/ChRIS_store_ui/issues/14 and https://github.com/FNNDSC/ChRIS_store_ui/issues/102 - Let's wait until you are able to close those before taking on more so other applicants have a shot. 👍

**Comment by DivyanshiSingh** [comment]
Hey @mairin I have already raised a PR for #14

**Comment by mairin** [comment]
@DivyanshiSingh that's great! #102 has a lot of subtasks and a little bit of research so it might take a bit longer!

**Comment by Abhir-24** [comment]
@mairin can u assign me this currently I am working on this issue only

**Comment by DivyanshiSingh** [comment]
> @DivyanshiSingh that's great! #102 has a lot of subtasks and a little bit of research so it might take a bit longer!

Sure ...I am working on #102

**Comment by Abhir-24** [comment]
I have discovered the component causing this bug but I am having problem to find a solution to it.

![image](https://user-images.githubusercontent.com/56101022/113159664-a5382c80-91f1-11eb-8d24-e02d8092d88e.png)

Here the value of search is not changed when the page is changed. I searched as to how can the value of the Proptype be changed but couldn't find any helpful resource. If possible can u pls help me out how can I solve it @mairin

**Comment by mairin** [comment]
Hey @Abhir-24 - are you in the Matrix or Slack channel for the project? (They are linked, the same place) I asked @jennydaman about this and he has a patternfly4 branch of this that it could be helpful for you to try to see if you can reproduce the issue. I am asking him more about it, you might want to join the convo.

Here's the conversation thread in Slack:
https://fnndsc.slack.com/archives/C013F05ELDA/p1617205860037300

**Comment by Abhir-24** [comment]
Hi, @mairin , I am in the Matrix channel currently. I am not able to join the slack server due to other workspaces on my account. If possible, can I get an invite to join the slack server?

And yes I will look into the patternfly4 branch to see if I find something useful.

**Comment by jennydaman** [comment]
Invite to slack: https://slack.babymri.org

**Comment by Abhir-24** [comment]
thanks @jennydaman for the invite link. I ll contact you after two days regarding the issue as currently my exams are going on 😅. Hope you don't have any problem

**Comment by mairin** [comment]
Hi @Abhir-24 - let me know if you are still interested in this issue now that the Outreachy contribution period is over, or if we should clear you as the assignee for now.

**Comment by Abhir-24** [comment]
Hi, you can unassign me this issue. I caught covid during the period and hence couldn't work further for Outreachy.

**Comment by lumuchris256** [comment]
hi @mairin @jennydaman  , i am a successful outreachy intern 22 applicant  ,
i am taking a spin on this.
so far tried to reproduce this issue but seem not evident

![Screenshot from 2022-04-01 15-17-31](https://user-images.githubusercontent.com/59338693/161261882-bd9c6c4e-1dff-4277-abc5-5822b0cdbc57.png)

![Screenshot from 2022-04-01 15-17-20](https://user-images.githubusercontent.com/59338693/161261850-111040c8-dbbb-4af1-bcb9-f3ad0c0476d5.png)
 any other pointers?

**Comment by jennydaman** [comment]
It is likely that this issue is stale.
