### ISSUE TITLE
TODO: ChRIS Store fit & finish - a lot of minor fixes like replacing non-functional front page icons, filling it developer call to action copy

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_store_ui#102]

**Comment by mairin** [comment]
@stan-green-pm is interested in this ticket.

**Comment by DivyanshiSingh** [comment]
Hey, @mairin I would like to take this issue.

**Comment by DivyanshiSingh** [comment]
I have set up the project into my local system and saw that we have non-functional buttons, icons, and some arbitrary texts (Lorem Ipsum). How would you like me to proceed with this issue? Please provide more information.

**Comment by mairin** [comment]
The 4 apps (FreeSurfer can stay) listed here need to be replaced with names of apps that are in the store right now:

![Screenshot_20210331-075800_Firefox](https://user-images.githubusercontent.com/799683/113141244-73c25f80-91f7-11eb-8981-24eb4debfecb.jpg)

Take a look at https://chrisstore.co/plugins and pick out 4. Let me know what you picked and we'll figure out here what icons to use.

Each of those plugins should have some text you can use in place of the lipsum dolor filler.

Browss our catalog -

Same here, just list the tools that are at https://chrisstore.co/plugins each under the correct category.

For the footer -

- copyright should be 2018-2021. Can you implement this so the last year is always the current year?
- About ChRIS should point to chrisproject.org
- Submit your plugin should point to /quickstart
- Contact Us should be a mailto for devel@chrisproject.org with subject "Contact from ChRIS Store"
- Report an issue should point to the github URL to report an issue for the ChRIS store (can you look up the url for this?)
- Request a plugin should be mailto devel@chrisproject.org with subject "ChRIS Store Plugin Request"
- We dont have anything for the last 3 yet. Can you file a ticket for someone to come up with content for those, and comment out those three items for now? (help, privacy, terms)

For the developers call to action - the text that should be here is at the top of /quickstart. Can you duplicate that text here on the front page and have a "learn more" button to transition over to /quickstart?

Hope this makes sense, let me know if you get stuck!

**Comment by DivyanshiSingh** [comment]
Hey @mairin as mentioned above by you to choose 4 apps, I want to ask whether I have to choose them randomly. If yes, then the following are my choices:
1) pI-freesurfer-pp
2)pI-z2labelmap
3)pI-dsdircopy
4)pI-fetal-brain-mask

**Comment by mairin** [comment]
Hey @DivyanshiSingh that seems fine except we already have freesurfer (its the 5th) so pick another one for that.

**Comment by mairin** [comment]
Also disregard the footer stuff, thats covered by a separate ticket! 🤦‍♀️

**Comment by DivyanshiSingh** [comment]
Ok Ok ...I actually started working on the footer

**Comment by mairin** [comment]
Sorry abt that!

**Comment by DivyanshiSingh** [comment]
And another app could be:
pI-flip

**Comment by DivyanshiSingh** [comment]
Hey, @mairin I have selected the apps. Can you please tell me about the icons for the same?

**Comment by DivyanshiSingh** [comment]
@mairin any updates on this?

**Comment by mairin** [comment]
Hey @DivyanshiSingh - don't block on the icons, just use the Freesurfer icon on each item. (from chat.) I have less availability than I thought to get some icons together for you. If you have time and can brainstorm ideas for the ones that don't have icons, that would be helpful but don't worry if not.

**Comment by mairin** [comment]
Hey @jennydaman this issue still depends on https://github.com/FNNDSC/ChRIS_store_ui/pull/124

**Comment by jennydaman** [comment]
Solution proposal in https://github.com/FNNDSC/ChRIS_store_ui/issues/150
