### ISSUE TITLE
Show warning when docker image ends with ":latest"

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#113]
It is bad practice to use the `:latest` docker images, because the app (e.g. its command-line options) are subject to change in later versions.

The warning message might briefly explain [why it's a bad practice](https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Best-Practices#versioning), and suggest a remedy:

```bash
docker tag user/pl-mything:latest user/pl-mything:1.0.1
docker push user/pl-mything:1.0.1
```

**Comment by DivyanshiSingh** [comment]
Hey, @mairin I would like to work on this issue. Please assign me this.

**Comment by DivyanshiSingh** [comment]
Hey, @jennydaman can you provide some more information that will help me in solving this issue. 
I am not getting where to write the script for testing the build command.

**Comment by jennydaman** [comment]
> script for testing the build command

I am not sure what you mean by this.

Here's a hacked mock-up

![Screenshot](https://user-images.githubusercontent.com/20404439/113597378-9e525500-9609-11eb-8fea-130fcdd72d46.png)

Here the user is trying to create a plugin. They've specified the "Docker Image" (`dock_image`) as `fnndsc/pl-surf`. This is a bad practice so we show the warning message 

> Please tag your Docker image by version.

In that box, you could include a link to a help article explaining why and how, or design a layout to provide immediate help. e.g. show a code block

```bash
docker tag fnndsc/pl-surf fnndsc/pl-surf:1.0.1
docker push fnndsc/pl-surf:1.0.1
```

If the user's input for `dock_image` ends with `:latest` instead, then show the warning

> The `:latest` tag is discouraged. Please tag your Docker image by version.

Input validation code is found here

https://github.com/FNNDSC/ChRIS_store_ui/blob/0db51860bf76c3002785944edb13a62347194af2/src/components/CreatePlugin/CreatePlugin.js#L223-L242

**Comment by DivyanshiSingh** [comment]
Ok, I got it @jennydaman.
I was moving in the wrong direction...This is a great help. Thank you
