### ISSUE TITLE
Show failed network requests in the UI

### ISSUE THREAD

**Issue by jdtzmn** [FNNDSC/ChRIS_store_ui#13]
Error messages should exist somewhere in the UI to inform the user if the page has trouble loading.

**Comment by DivyanshiSingh** [comment]
Hey, @mairin I would like to work on this. Please assign me this issue.

**Comment by jennydaman** [comment]
@mairin imo this kind of issue would seem to be something better to be worked on _after_ PatternFly4 rewrite

**Comment by DivyanshiSingh** [comment]
Can you point me to the page where API fails and we don't get any notifications? @jennydaman

**Comment by jennydaman** [comment]
First, let's find places in the code which are responsible for doing network requests.

Interaction with the API is made easy with the `@fnndsc/chrisstoreapi` npm package. Typical usage would be

```javascript
import Client from '@fnndsc/chrisstoreapi';

[...]

this.client = new Client(storeURL, auth);
```

And then something like

https://github.com/FNNDSC/ChRIS_store_ui/blob/0db51860bf76c3002785944edb13a62347194af2/src/components/Plugins/Plugins.js#L84-L91

To find all usages of this, we can search for the string `client.`
I will use the `grep` tool, you can use Github search, or your IDE's full-text search.
(A great alternative is [`rg`](https://github.com/BurntSushi/ripgrep))

```
$ grep -Fnr 'client.' src/
src/components/Dashboard/Dashboard.js:40:    return client.getPlugins(searchParams)
src/components/Dashboard/Dashboard.js:59:      response = client.getPlugin(pluginId).then(plugin => plugin.delete());
src/components/Dashboard/Dashboard.js:77:      response = client.getPlugin(pluginId)
src/components/Plugins/Plugins.js:85:      const star = await this.client.createPluginStar({ plugin_name: plugin.name });
src/components/Plugins/Plugins.js:100:      const star = await this.client.getPluginStar(previousStarState.id);
src/components/Plugins/Plugins.js:118:        plugins = await this.client.getPlugins(searchParams);
src/components/Plugins/Plugins.js:136:    const stars = await this.client.getPluginStars();
src/components/CreatePlugin/CreatePlugin.js:261:      const resp = await client.createPlugin(pluginData, fileObj);
src/components/Plugin/Plugin.js:72:      const star = await this.client.createPluginStar({ plugin_name: name });
src/components/Plugin/Plugin.js:86:      const star = await this.client.getPluginStar(previousStarState.id);
src/components/Plugin/Plugin.js:99:        const plugin = await this.client.getPlugin(parseInt(pluginId, 10));
src/components/Plugin/Plugin.js:120:      const response = await client.getPluginStars({ plugin_name: pluginName });
```

Sometimes the client is wrapped in a try-catch and shows the error. For example,

https://github.com/FNNDSC/ChRIS_store_ui/blob/0db51860bf76c3002785944edb13a62347194af2/src/components/CreatePlugin/CreatePlugin.js#L260-L265

But this is not implemented everywhere, as from the [previous `Plugins.js` example above](https://github.com/FNNDSC/ChRIS_store_ui/blob/0db51860bf76c3002785944edb13a62347194af2/src/components/Plugins/Plugins.js#L84-L91).

All in all, a few things to consider:

- How can we handle network errors logically, using object-oriented programming in JavaScript?
- How can we show errors to the user using React JSX?
- Should we set a timeout for network requests?
- Should we handle errors specifically? (such as connection timeout, connection interrupted, or response not understood)

**Comment by DivyanshiSingh** [comment]
I am handling the network errors by making HttpApiCallError class that can handle the errors specifically and will return respective error messages according to the status code. Using these messages we can show an alert component that our request is failed.
I will raise a PR with the changes required.

**Comment by mairin** [comment]
Thanks for your work here @DivyanshiSingh - closing as complete.
