### ISSUE TITLE
Group plugins by the same name (but different versions) in the search results

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#131]
![screenshot](https://user-images.githubusercontent.com/20404439/114295109-1d63e500-9a71-11eb-8c2e-211a9c13a1ab.png)

Minimum effort solution: show version next to the name.

Best solution: group versions of the same plugin under the name.

**Comment by archanaserver** [comment]
Hi @jennydaman, I want to work on this issue. Can you please elaborate it more?

**Comment by jennydaman** [comment]
I cannot elaborate more other than providing mockup. Give me a few minutes....

**Comment by jennydaman** [comment]
I present the lazy solution using a lazy mockup:

![lazy mockup](https://user-images.githubusercontent.com/20404439/114295511-c3185380-9a73-11eb-91fc-f4f732b0c44b.png)


Or, with more effort, group versions under the same name so it says:

> **pl-demo**
> COVID-Net inference for chest x-ray
> mario <hanmario@bu.edu> created 6 days ago
> v1.0.1
> v1.0.2
> v1.0.3

Each version string is a hyperlink to the plugin page for the specific version.

**Comment by archanaserver** [comment]
but i'm sure i got your point @jennydaman, thanks!

**Comment by archanaserver** [comment]
Hie @jennydaman, I was working on this issue but seems like, i can't find same plugin name with it's different versions.

**Comment by jennydaman** [comment]
I do not understand what you mean.
example: https://chrisstore.co/plugins?q=pl-fetal-brain-mask

**Comment by NehalJain159** [comment]
@mairin @jennydaman ,I would like to work on this issue.Could you please assign this to me?

**Comment by archijaiswal** [comment]
I would like to take a look at this issue of it's still present. Please assign it to me.@jennydaman

**Comment by Anirudh4583** [comment]
hey @jennydaman can you provide an example link or a way to recreate this issue?

**Comment by jennydaman** [comment]
Hey @archijaiswal and @Anirudh4583, this issue is stale.
