### ISSUE TITLE
Bug in README.md

### ISSUE THREAD

**Issue by somya51p** [FNNDSC/ChRIS_store_ui#143]
In README.md,  On clicking **Licence** in line 'see the LICENSE.md file for details' , it is getting redirected to Page not Found.

' @jennydaman Please look into it, If it needs to be resolved I would like to work on it.

**Comment by jennydaman** [comment]
Thanks for bringing this to my attention. It's a quick and boring change so I just did it.
https://github.com/FNNDSC/ChRIS_store_ui/commit/3be6c1feb0135011105db0d6a0c310274189d51c

**Comment by somya51p** [comment]
sure maam

**Comment by jennydaman** [comment]
Are you looking for things to do? lmk

**Comment by somya51p** [comment]
Yes, for a good start. I was working on this issue https://github.com/FNNDSC/ChRIS_ui/issues/166, but it is taking time I have tried many things.

**Comment by jennydaman** [comment]
You should've said so! I will take a look at the issue right now and discuss it with you if I figure something out.

**Comment by somya51p** [comment]
Okay maam, Thanks a lot for considering that.
