### ISSUE TITLE
Search bar not working on pf4 branch

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#146]
@DivyanshiSingh do you want to take a look?

**Comment by DivyanshiSingh** [comment]
Yeah sure @jennydaman

**Comment by DivyanshiSingh** [comment]
As i can see #134 was merged in master and not pf4 so I am planning to implement Autocomplete and fix the search in pf4 @mairin @jennydaman

**Comment by DivyanshiSingh** [comment]
@jennydaman  @mairin please have a look at the PR and let me know the required changes.
