### ISSUE TITLE
Preprare pf4 branch for public eyes: hard-code featured plugins and icons

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#169]
I have forward-ported important features from master into pf4, such as #119 and #139 

With #161, `pf4` is looking like a working product! It is all thanks to our 2021 Outreachy applicants :tada:. Perhaps we should focus on wrapping things up and hitting a milestone.

#102 is the last thing on the table before @rudolphpienaar would consider the ChRIS_store_ui "good for public eyes."

In the branch [pf4-prod](https://github.com/FNNDSC/ChRIS_store_ui/tree/prod-pf4) I've removed the categories display from the welcome page, it would have been too much work for our milestone.

An attempt was made to address #102 in #124, but @mairin suggested a more advanced solution leading to #150. However, in the interest of time, we should not move forward with #150. Instead we should hard-code 4-5 good plugins from https://chrisstore.co into the user interface and hard-code their icons.

**Comment by jennydaman** [comment]
@DivyanshiSingh you might be interested with this issue and pick up from #124

**Comment by DivyanshiSingh** [comment]
Yes, I would be working on it @jennydaman

**Comment by DivyanshiSingh** [comment]
Where can I find the icons? Do I need to change the categories section?

**Comment by jennydaman** [comment]
Let's leave the categories section commented out for now.

Please hold on this issue for maybe a day, we need to circle around with @rudolphpienaar and @mairin about which plugins to feature.

I would suggest:

- [pl-fastsurfer_inference](https://next.chrisstore.co/plugin/44)
- [pl-infantfs](https://next.chrisstore.co/plugin/78)
- [pl-irtk-reconstruction](https://next.chrisstore.co/plugin/85)
- [pl-ANTs_N4BiasFieldCorrection](https://next.chrisstore.co/plugin/77)
- [pl-civet](https://next.chrisstore.co/plugin/2)

Fortunately, it's easy to come up with icon ideas for these 5.

**Comment by jennydaman** [comment]
Icone could be from:

- fastsurfer: we'll have to create one
- InfantFS: FreeSufer icon
- IRTK: use BioMedIA's logo, (not the Comic Sans initialism) https://biomedia.doc.ic.ac.uk/software/irtk/
- ANTs: ... an ant? Or the icon from their Github org: https://github.com/ANTsX
- CIVET: CIVET icon https://mcin.ca/technology/civet/

**Comment by DivyanshiSingh** [comment]
Hey, @jennydaman should I start on this issue if the plugins and icons are final?

**Comment by jennydaman** [comment]
Yes.

The official icons I've linked to above don't necessarily fit the look and feel of _ChRIS_. They're okay to use for now. We can make a quick and easy icon for FastSurfer.

Sometime, the icons should be redesigned to match the _ChRIS_ look and feel. We should also discuss with @mairin in case she has any take on icons.

**Comment by DivyanshiSingh** [comment]
Hey @jennydaman @mairin  how can I get the SVG form of the above-mentioned icons? Also, do I need to make an icon for fastsurfer? Any help on this.

**Comment by DivyanshiSingh** [comment]
Any updates?

**Comment by jennydaman** [comment]
@DivyanshiSingh sorry for missing your question. While we wait for SVGs from @mairin, we should use PNG placeholders -- either use the old ones or project official icons. They'll be ugly but it doesn't matter for now, we will replace them later.

**Comment by jennydaman** [comment]
@DivyanshiSingh sorry for missing your question. While we wait for SVGs from @mairin, we should use PNG placeholders -- either use the old ones or project official icons. They'll be ugly but it doesn't matter for now, we will replace them later.
