### ISSUE TITLE
Search autocomplete selection with arrow keys

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#170]
Autocomplete was implemented in #154

Pressing either the <kbd>Up</kbd> or <kbd>Down</kbd> arrow keys should move the selection of which autocomplete suggestion to accept. The current behavior is that pressing <kbd>Down</kbd> just moves the cursor to the end.

@DivyanshiSingh do you want to take this issue?

**Comment by DivyanshiSingh** [comment]
Yes, @jennydaman I would take this issue.
