### ISSUE TITLE
Use props instead of state where possible

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#183]
Now that we're using React hooks, we get many warnings like

```
./src/components/Welcome/components/WelcomeCategories/WelcomeCategories.js
  Line 7:22:  'setCategories' is assigned a value but never used  no-unused-vars
```

In these situations it is better to use props instead of state.

https://github.com/FNNDSC/ChRIS_store_ui/blob/d9c388261ae4cc8d091d8885c3a8cb4b95c2438d/src/components/Welcome/components/WelcomeCategories/WelcomeCategories.js#L7

**Comment by EUGINELETHAL** [comment]
let me handle this

**Comment by somya51p** [comment]
@jennydaman I wish to work on this one.

**Comment by Akhil132-dev** [comment]
I want work on this it very simple warnings you can get out of ride very easily
