### ISSUE TITLE
Replace shortened links with real links

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#199]
https://github.com/FNNDSC/ChRIS_store_ui/blob/0d150714d6dada40831251796d49e735f6fa756c/src/components/Developers/components/Instructions/Instructions.js#L10

- the link here is outdated
- URL shorteners do not respect privacy

This needs to be changed to https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart

**Comment by jennydaman** [comment]
We should replace all of them.

```bash
$ rg bit.ly
src/components/Developers/components/Instructions/Instructions.js
10:        <a className="instructions-source" href="http://bit.ly/2KghHdY">[source]</a>
36:                    href="http://bit.ly/2Iih52m"
45:                    href="http://bit.ly/2KghHdY"
141:              <a href="http://bit.ly/2yzbRzF">simple <strong>fs</strong> plugin</a>
143:              <a href="http://bit.ly/2KbHosS">simple <strong>ds</strong> plugin</a>
156:              consult the <a href="http://bit.ly/2ltTJ0w">wiki</a> to learn how to register it to
```

**Comment by SugatoBagchi** [comment]
Hi,

I would like to work on this issue. Can you please assign it to me?

Thank you.
