### ISSUE TITLE
Case-insensitivity in plugin names

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#228]
Warn users when attempting to use a plugin name which already exists but has a different case, e.g. pl-nAme and pl-namE

**Comment by zrthxn** [comment]
A frontend solution for this could be made as follows.

- Query for all plugin metas when the creation form loads
- Extract only names and `toLowerCase()` for all
- In the plugin name text input, `onChange = value => names.includes(value.toLowerCase())`
