### ISSUE TITLE
Implement PyPI’s user collaborators model on the ChRIS store UI.

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_store_ui#245]
The ChRIS store frontend JS client has new methods to add collaborators to a plugin (`Client.createPluginCollaborator`), show a plugin’s collaborators and their role (`PluginMeta.getCollaborators`) and for each user the plugins it collaborates on (`Client.getCollabPluginMetas`).

https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/client.js~Client.html#instance-method-createPluginCollaborator
https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/client.js~Client.html#instance-method-getCollabPluginMetas
https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/pluginmeta.js~PluginMeta.html#instance-method-getCollaborators

Implement this collaborators model in the ChRIS store UI. Basically a similar user interface as PyPI’s: https://pypi.org

Following PyPI’s UI design each plugin meta should have a link to a list of collaborators. When an authenticated user clicks there she gets to that list and if she is a plugin’s owner then she can add a new collaborator by entering username + role and clicking a button. Currently the only two possible roles are 'O' (owner) and 'M' (maintainer).

**Comment by mairin** [comment]
@EUGINELETHAL Is it safe to close this issue as complete?

**Comment by EUGINELETHAL** [comment]
it is a full feature, worked on some of it planning to continue with the
rest sometime later, yes but we can  close the issue

**Comment by mairin** [comment]
Closing as fixed, thanks :)
