### ISSUE TITLE
Add an Eye Icon on password Area to show Password When A user Clicks on it

### ISSUE THREAD

**Issue by sherrif10** [FNNDSC/ChRIS_store_ui#275]
This is basically to add an eye icon on the password area for the user to click on to confirm whether the password is correct.
cc  @mairin  @jennydaman . Is this worth looking to hear from your views.
![chr](https://user-images.githubusercontent.com/48015736/163177318-04d4d6f0-a6e6-4d45-8dd5-110b658dd673.png)

**Comment by Pattygeek** [comment]
@jennydaman I would like to work on this issue.

**Comment by sherrif10** [comment]
Great to see you intrested in this issue. @jennydaman  could you assigne her to this issue, am willing to review it.

**Comment by somya51p** [comment]
Hey @sherrif10, there is already an issue created for the same under issue #152.

**Comment by sherrif10** [comment]
Sure I can close this ticket as @mairin  said.
