### ISSUE TITLE
Docker run throws error

### ISSUE THREAD

**Issue by archijaiswal** [FNNDSC/ChRIS_store_ui#278]
On starting the ChRIS store UI development server using docker on Ubuntu 20.04, `docker run` throws error
`invalid reference format: repository name must be lowercase
`

**Comment by AryaArunB** [comment]
I think this might be some issue on your local env. The best way to discuss this would be on the element chat.

**Comment by archijaiswal** [comment]
Thanks @AryaArunB for the advice. Got this fixed, the issue was something with the way directory name is specified and the fix is to quote the path.
