### ISSUE TITLE
404ing page

### ISSUE THREAD

**Issue by yarikoptic** [FNNDSC/ChRIS_store_ui#289]
from https://chrisstore.co/  for freesurfer goes to https://chrisstore.co/plugin/44 which 404s

**Comment by OmkarAcharekar** [comment]
@yarikoptic The issue has been fixed

**Comment by jennydaman** [comment]
Fixed in https://github.com/FNNDSC/ChRIS_store_ui/commit/bff1329b2b11fd5f093aea84bc8ac16f1872b742, will be deployed soon :tm: !
