### ISSUE TITLE
Typo error in components html code

### ISSUE THREAD

**Issue by VictoriaAjala** [FNNDSC/ChRIS_store_ui#292]
Found an error in the plugin store html text. This good be a first timer issue.

![Screenshot from 2022-10-07 12-25-11](https://user-images.githubusercontent.com/102407780/194542430-22e07574-c5ba-4961-be58-d73528bb599c.png)

Code can be found here:

[https://github.com/FNNDSC/ChRIS_store_ui/blob/master/src/components/Welcome/components/WelcomeCategories/WelcomeCategories.jsx](url)

**Comment by VictoriaAjala** [comment]
@jennydaman Kindly review this. Thanks

**Comment by jennydaman** [comment]
Thanks for pointing this out, I've adjusted the wording. 6efcbb2b1ff5c74ae536f79df7dffbcbdef455b9
