### ISSUE TITLE
Change create user flow

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_store_ui#35]
Developer page should Not have the form for creating an account
dashboard should keep the current behavior of appearing only once a dev has logged in.
Creating a dev account should be on a new page:
Should only show the signup form (currently on the Developers page)

@jbernal0019 @rudolphpienaar

**Comment by jcaianirh** [comment]
@mairin any design input on how to carry this out visually?

**Comment by mairin** [comment]
@jcaianirh what i would suggest:

not logged in:

- developers tab is the same with sign up form / call to action

logged in:

- dashboard loads, sign up form gone, link to create new account gone, the detailed info about getting started could be there but maybe hidden under a disclosure triangle?

Does this make sense?

**Comment by jcaianirh** [comment]
@mairin I like the idea of keeping both pages. There is a lot of good info on that dev page. Can we keep the dashboard and the dev page, but hide the signup form if the user has logged in?  So direct the user flow from developer to dashboard after a successful signin, but keep the dev page for reference.

**Comment by mairin** [comment]
i dont have a visual in front of me but i agree the developers page sans form should be accessible whether or not youre logged in / signed up. 

would it make sense to have a "developer guide" card in the dashboard that points to it?

**Comment by jcaianirh** [comment]
@mairin updated flow in above pr.

**Comment by jcaianirh** [comment]
closing issue.
