### ISSUE TITLE
Developer Signup page seems to be broken

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_store_ui#46]
Developer Signup page seems to be broken in ChRIS_store_ui after merge of pull request for #44
The fields to signup have become immutable 

![](https://files.slack.com/files-pri/T04FLFU8G-FGB1ZQ8EB/screen_shot_2019-02-18_at_11.18.20_am.png)

**Comment by gagansk** [comment]
The functionality is working as expected.

**Comment by jcaianirh** [comment]
Thanks @gagansk
