### ISSUE TITLE
Refreshing dashboard with multiple plugins causes duplication of name 

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_store_ui#50]
Step 1 . create 3 plugins in the dashboard
step 2. delete a plugin
step 3. view existing plugins. there are duplicate plugins listed in the dashboard. though the deleted plugin is gone.

**Comment by gagansk** [comment]
@jcaianirh I am unable to see the deleted plugins appear in the Dashboard. However, even if no delete operation is performed, on refreshing the page, two plugins with the same name appear. Is this the behaviour you wanted to report? or something in terms of delete?

**Comment by jcaianirh** [comment]
@gagansk yes that is the behavior for this issue. thanks!

**Comment by gagansk** [comment]
Steps to reproduce the bug:

1. Create more than two plugins.
2. Refresh the page.

Current Behaviour:
The number of plugins will remain the same but the plugin names will be duplicated.

**Comment by gagansk** [comment]
Closed with PR #54
