### ISSUE TITLE
Protected routes solution for pages that require credentials needed

### ISSUE THREAD

**Issue by jcaianirh** [FNNDSC/ChRIS_store_ui#51]
In the Chris UI we have a protected routes solution that we can also use here in the store. https://github.com/rebecabkerr/ChRIS_ui/blob/feature/feed/src/components/common/PrivateRoute.tsx

https://github.com/rebecabkerr/ChRIS_ui/blob/feature/feed/src/routes.tsx

**Comment by gagansk** [comment]
@jcaianirh , What are the features we are supposed to make private? Dashboard appears only after login already.

**Comment by jcaianirh** [comment]
@gagansk if a user bookmarks dashboard it should be protected

**Comment by jcaianirh** [comment]
closed with this pr: https://github.com/FNNDSC/ChRIS_store_ui/pull/60
