### ISSUE TITLE
Plugin’s detail page should also expose the plugin’s id

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_store_ui#71]

**Comment by sonylomo** [comment]
Hey, is this an example of plugin's detail page that's supposed to show the plugin id?
![plugin details](https://user-images.githubusercontent.com/49971500/113189485-e79a5180-9263-11eb-8489-04a08c4890f5.png)

**Comment by sonylomo** [comment]
@mairin, Can I work on this issue?

**Comment by mairin** [comment]
Hey @sonylomo - can you add it in the right hand sidebar, under the contributor list? You can use the same format as the stuff that's there, field name: then on the next line the value.

![plugin-details_readme 3](https://user-images.githubusercontent.com/799683/113725610-7b837780-96c1-11eb-939f-6ed87468c529.png)

**Comment by mairin** [comment]
Thanks @sonylomo - great work :)
