### ISSUE TITLE
A “copy url button” should be added to the plugin’s detail page.

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_store_ui#72]

**Comment by mairin** [comment]
Is this for copying the ChRIS store URL, the dockerhub URL, or the github URL? (or all of the above?) Should it be just the URL or commands?

**Comment by jbernal0019** [comment]
It is a convenient way of copying the plugin's ChRIS store url to the clipboard, eg.: `http://localhost:8010/api/v1/plugins/ 1/`

**Comment by mairin** [comment]
![Screenshot from 2020-08-04 16-27-20](https://user-images.githubusercontent.com/799683/89341679-a66b8680-d66f-11ea-856e-cb2e0a49dd3c.png)
![Screenshot from 2020-08-04 16-29-30](https://user-images.githubusercontent.com/799683/89341708-b2574880-d66f-11ea-9df1-fd0b51996d59.png)

Quick screenshots of the design we came up with in chat.

**Comment by mairin** [comment]
It appears this was merged so I'm closing.
