### ISSUE TITLE
A clickable star button should be added to the plugins  list and detail pages. The user will need to be logged in to be able to click that button. It can only be clicked once per user.

### ISSUE THREAD

**Issue by jbernal0019** [FNNDSC/ChRIS_store_ui#73]

**Comment by jramcast** [comment]
hey @jbernal0019, I'm taking a look at this one. Could you assign it to me?

**Comment by jramcast** [comment]
Are we handling the scenario where a user wants to delete the star from a plugin? If this is the case, then we should allow the star to be clicked more than once.

BTW, what's the endpoint we should be calling when the star is clicked? This one? -> https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/pluginstar.js~PluginStar.html

**Comment by jbernal0019** [comment]
@jramcast Yes, the user can delete the star from a plugin. When the user first clicks on the plugin's star the plugin becomes a user's favorite. If the user clicks again on the star then the plugin is no longer a favorite. Users need to be logged in to be able to star a plugin.
The API calls are:

1. To star a plugin:  https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/client.js~Client.html#instance-method-createPluginStar

`resp = client.createPluginStar({plugin_name:<name>})`  

2.  To "unstar" a plugin: 
If you know the `id` of the star then:  https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/client.js~Client.html#instance-method-getPluginStar

`resp = client.getPluginStar(<id>)` 
  .then(star => star.delete())
  .catch(error => {
    window.console.log('Error!!!: ', error);
  });

You can also search for the star based on a plugin's name: https://fnndsc.github.io/fnndsc/chrisstoredoc/class/src/client.js~Client.html#instance-method-getPluginStars
