### ISSUE TITLE
ChRIS Store: Update plugin details page design to account for README display, parameters, and version listing

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_store_ui#81]
(@mairin)

**Comment by mairin** [comment]
Here is what the plugin details screen looks like when you first come to it. 

The orange/yellow labels show where the data comes form from the API. Items in orange are in the plugin-meta object, items in yellow are in the plugin object and need to be made available for the plugin-meta as well.

There are three main tabs on this screen:

- **Overview:** Displays a nicely-rendered copy of the README.rst or README.md files from the plugin's repo. It displays the README for the latest version of the repo. 
- **Parameters:** Displays a nicely-rendered copy of the plugin parameter list available via the ChRIS Store API. Parameter lists are versioned, so there is a version dropdown to switch versions in case you need access to an older version of the parameter lists. It is not expected that there will be many changes between versions.
- **Versions:** Displays the list of available versions of the plugin. Will be the same as the list in the parameter version dropdown.  Mockup WIP.

### Overview tab visible
![plugin-details_readme 1](https://user-images.githubusercontent.com/799683/89223173-570c5400-d5a4-11ea-9561-14a7a645b57f.png)

### Parameters tab visible
![plugin-details_parameters 3](https://user-images.githubusercontent.com/799683/89223386-b23e4680-d5a4-11ea-8b1d-167986e0c4e4.png)

Versions tab to be uploaded in another comment when complete.

**Comment by jbernal0019** [comment]
@mairin These look great!

**Comment by junaruga** [comment]
I like it.

## Overview page

I like the following parts. It's user friendly.

* Left side of the page: similar with the `man` page.
* Right side of the page: similar with Github repository top page.

**Comment by anujsingla** [comment]
@mairin look great! Yesterday I have changed Developer nav to Quick Start.
Please change in the design also. Developer -> Quick Start
PR -> https://github.com/FNNDSC/ChRIS_store_ui/pull/85
cc: jbernal0019

**Comment by mairin** [comment]
Here's the updated version of the plugin details page - the major change here is removing the versions tab, and adding a dropdown to switch versions. One more mockup pending is the list of versions you can get by clicking the link next to the versions dropdown control.

![plugin-details_meta-plugin_revision_readme 3](https://user-images.githubusercontent.com/799683/96027866-894cf400-0e26-11eb-88ec-01e1c2a5eef1.png)

**Comment by mairin** [comment]
List of mockup issues to address:

[  ] Add new version dropdown to all mockup tabs
[  ] Add new tab for "Configuration" to display 'min_number_of_workers', 'max_number_of_workers', 'min_cpu_limit', 'max_cpu_limit', 'min_memory_limit', 'max_memory_limit', 'min_gpu_limit', 'max_gpu_limit' which are all overrideable at runtime
[  ] Remove "v" from version number
[  ] ChRIS store admins for a given plugin are != as contributors. Contributors is a free-form field, admins are ChRIS store users. Separate contributors out as a separate piece of metadata displayed from admins
[  ] Mark explicitly what date is meant for the upper right corner and the individual creation dates for the plugin versions.
[  ] Per plugin version mark version creation date as "release date"
[  ] Public repo field is editable without JSON upload, make editable for logged in admin users

**Comment by mairin** [comment]
Here's a good set of mockups that addressed all of the above except the public repo field editing - I am thinking just an inline editable form field triggered by a link next to the field on the front page, only visible by a logged in admin? @jbernal0019 I'd love a review of these if you wouldnt mind!

### Front Page / README Tab 
![plugin-details_readme 3](https://user-images.githubusercontent.com/799683/96189127-ee2f4980-0f0d-11eb-99c2-ae630122e474.png)

### Parameters Tab
![plugin-details_parameters 4](https://user-images.githubusercontent.com/799683/96189168-0010ec80-0f0e-11eb-8e42-74457b558834.png)

### Configuration Tab
![plugin-details_configuration 1](https://user-images.githubusercontent.com/799683/96189178-056e3700-0f0e-11eb-8dab-3a6653993141.png)

**Comment by jbernal0019** [comment]
Nice @mairin!

Yes, the link to edit public repo should only be visible by a logged in admin.

**Comment by jbernal0019** [comment]
@mairin There should also be a way for a logged in admin to add a new admin given the ChRIS store username.

**Comment by anujsingla** [comment]
@mairin Nice design.

**Comment by mairin** [comment]
@jbernal0019 @anujsingla could we handle the case of a logged in admin adding a new admin (or removing a current admin?) similarly to public repo editing noted above... if you're admin and logged in, you'll see a "add new admin" link at the top of the admin section, and maybe little (X) buttons next to each admin to delete individual admins (with a conf dialog?)

**Comment by jbernal0019** [comment]
@mairin Yes, I think a logged in admin should see an "add new admin" link that allows him to add a new admin to the repo. Currently, once a new admin is added to the repo it can not be deleted as that admin might have published new versions of the plugin. One admin can not delete another admin.

**Comment by mairin** [comment]
I had opened https://github.com/FNNDSC/ChRIS_store_ui/issues/103 to track adding the ability to add a new admin to the repo. Closing this since it's merged.
