### ISSUE TITLE
ChRIS Store: Implement HTML/CSS for redesigned plugin details page so it is ready for wiring with React.

### ISSUE THREAD

**Issue by mairin** [FNNDSC/ChRIS_store_ui#86]
We need HTML/CSS implementation of the mockups in https://github.com/FNNDSC/ChRIS_store_ui/issues/81

This issue is for @mindreeper2420 - waiting for team access to properly assign it.

**Comment by junaruga** [comment]
@mindreeper2420 How is this work, Adam?

**Comment by mairin** [comment]
Closing since this is merged
