### ISSUE TITLE
Footer stuff

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/ChRIS_store_ui#98]
- [x] footer nav links are... not links
- [x] copyright message outdated
- [x] footer not expanded to bottom of page if main content is too small

**Comment by sonylomo** [comment]
Hey @mairin, I'm an Outreachy Applicant and I'd like to work on this issue.

**Comment by mairin** [comment]
All yours, @sonylomo !

**Comment by sonylomo** [comment]
What should I add as the links to: help, terms & conditions and also the Privacy policy?

**Comment by mairin** [comment]
Good q @sonylomo , here's what I suggest:

For the footer -

- copyright should be 2018-2021. Can you implement this so the last year is always the current year?
- About ChRIS should point to chrisproject.org
- Submit your plugin should point to /quickstart
- Contact Us should be a mailto for devel@chrisproject.org with subject "Contact from ChRIS Store"
- Report an issue should point to the github URL to report an issue for the ChRIS store (can you look up the url for this?)
- Request a plugin should be mailto devel@chrisproject.org with subject "ChRIS Store Plugin Request"
- We dont have anything for the last 3 yet. Can you file a ticket for someone to come up with content for those, and comment out those three items for now? (help, privacy, terms)

**Comment by sonylomo** [comment]
should the copyright statement be: "Boston Children's Hospital Fetal-Neonatal Neuroimaging and Developmental Science Center" or just remain as it is with only the years changed?

**Comment by mairin** [comment]
@sonylomo I would keep it the same and just update the latter year. And if you can have the latter year set to the current year instead of hard coded to 2021 that would be great!

**Comment by sonylomo** [comment]
Yep, I'll do that

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/ChRIS_store_ui/pull/116
